# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 979d27e52dedee27d9b2eb8debf8dc7a3f600ce881e50ddb935d45cc6d05a91f2f747c49d4478cf0af6c1a505c991086322ba5caab02ae00ad84d312d441a5e2

test:
  secret_key_base: 257ce12fb5550e164974a282998d325eae04787f154e2b0c9cff57650b1f3424ff81eee11d9e2522e7452d7e7ad94c148651fd5ac0891caa32ae612bf4c6526f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
